flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:eklinkhammer/neural-algorithms
    commit: master
extra-deps:
- KdTree-0.2.2.1
- hnn-0.3
- normaldistribution-1.1.0.3
- repa-3.4.1.3
- repa-algorithms-3.4.1.2
resolver: lts-9.6
